name: Selenium Tests

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Cucumber tags to run (e.g., @smoke, @regression). Leave empty to run all tests.'
        required: false
        default: ''
  schedule:
    # Runs at 9:00 AM and 9:00 PM UTC every day
    - cron: '0 9,21 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and Run Tests in Docker
      run: |
        # Build Docker image
        docker build -t selenium-tests .
        
        # Run tests in Docker
        if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ github.event.inputs.tags }}" ]; then
          docker run --rm -v "$(pwd)/target:/app/target" selenium-tests mvn clean test "-Dcucumber.filter.tags=${{ github.event.inputs.tags }}"
        else
          docker run --rm -v "$(pwd)/target:/app/target" selenium-tests mvn clean test
        fi
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          target

    - name: Generate Cucumber Report
      if: always()
      uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "target/cucumber-reports/CucumberTestReport.json" 